version: '3'

services:
  mysql_server:
    image: mysql:latest
    container_name: mysql_server
    networks:
      - bot_telegram_devel
    environment:
      MYSQL_ROOT_PASSWORD: vqTZQcue0f1VY4A9
      MYSQL_DATABASE: TeleBotDevelDB
      MYSQL_USER: TeleBotDevel
      MYSQL_PASSWORD: Mx7Sme5RSvXPW0EQyCCQedQG
      USERNAME: 6119375027
      NAMA_USER: Tamara
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --bind-address=0.0.0.0

  bot_valins_ta-sdi_devel:
    build: ./
    container_name: telebot
    depends_on:
      - mysql_server
    links:
      - mysql_server
    networks:
      - bot_telegram_devel
    volumes:
      - ./files:/files

networks:
  bot_telegram_devel:

volumes:
  mysql_data:
    external: true

