version: '3'

services:
  mysql_server:
    image: mysql:latest
    container_name: mysql_server
    networks:
      - bot_telegram_devel
    environment:
      MYSQL_DATABASE: TeleBotDevelDB
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      TELEBOT_USER: TeleBotDevel
      NAMA_USER: Muhammad Ivan Wiryawan
      USERNAME: 1139987918
    ports:
      - "3307:3306"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./replace.sh:/replace.sh
      - ./initialization.sql:/tmp/init.sql:ro
      - ./change_telebot_pass.sql:/tmp/change_telebot_pass.sql:ro
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./always-initdb.d:/always-initdb.d
      - ./init_status.txt:/init_status.txt
      - mysql_data:/var/lib/mysql
    entrypoint: /entrypoint.sh
    command: ["mysqld"]

  bot_valins_ta-sdi_devel:
    image: bot_valins_ta-sdi_devel
    build: ./
    container_name: telebot
    init: true
    depends_on:
      - mysql_server
    links:
      - mysql_server
    networks:
      - bot_telegram_devel
    environment:
      APP_TMP_DATA: /tmp
      BOT_TOKEN: 5874249633:AAFZROBcQdfp4-tkE8lXOqV2H2uSb2oNHOY
      MYSQL_DATABASE: TeleBotDevelDB
      MYSQL_HOSTNAME: mysql_server
      MYSQL_PORT: 3306
      TELEBOT_USER: TeleBotDevel
    volumes:
      - ./files:/files
      - ./init_status.txt:/init_status.txt
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./always-initdb.d:/always-initdb.d

networks:
  bot_telegram_devel:

volumes:
  mysql_data:
    external: true

