version: '3.1'

services:
  mysql_server:
    image: mysql:latest
    container_name: mysql_server
    networks:
      - bot_telegram_devel
    environment:
      MYSQL_DATABASE: TeleBotDevelDB
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      NAMA_USER: Muhammad Ivan Wiryawan
      MYSQL_USER: TeleBotDevel
      MYSQL_PASSWORD_FILE: /run/secrets/db_telebot_password
      USERNAME: 1139987918
    ports:
      - "3307:3306"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./replace.sh:/replace.sh
      - mysql_data:/var/lib/mysql
      - ./init.sql:/tmp/init.sql
    command: ./entrypoint.sh /tmp/init.sql /docker-entrypoint-initdb.d/init.sql
    secrets:
      - db_root_password
      - db_telebot_password

  bot_valins_ta-sdi_devel:
    image: bot_valins_ta-sdi_devel
    build: ./
    container_name: telebot
    depends_on:
      - mysql_server
    links:
      - mysql_server
    networks:
      - bot_telegram_devel
    environment:
      APP_TMP_DATA: /tmp
      BOT_TOKEN: 5874249633:AAFZROBcQdfp4-tkE8lXOqV2H2uSb2oNHOY
      MYSQL_DATABASE: TeleBotDevelDB
      MYSQL_HOSTNAME: mysql_server
      MYSQL_PORT: 3306
      MYSQL_USER: TeleBotDevel
      MYSQL_PASSWORD_FILE: /run/secrets/db_telebot_password
    volumes:
      - ./files:/files
    secrets:
      - db_telebot_password

networks:
  bot_telegram_devel:

volumes:
  mysql_data:

secrets:
  db_root_password:
    external: true
  db_telebot_password:
    external: true

