version: '3'

services:
  mysql_server:
    image: mysql:latest
    container_name: mysql_server
    networks:
      - bot_telegram_devel
    environment:
      MYSQL_ROOT_PASSWORD: vqTZQcue0f1VY4A9
      MYSQL_DATABASE: TeleBotDevelDB
      TELEBOT_USER: TeleBotDevel
      TELEBOT_PASSWORD: Mx7Sme5RSvXPW0EQyCCQedQG
      USERNAME: 1139987918
      NAMA_USER: Muhammad Ivan Wiryawan
    ports:
      - "3307:3306"
    command: ./entrypoint.sh
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./replace.sh:/replace.sh
      - mysql_data:/var/lib/mysql
      - ./initialized.sql:/docker-entrypoint-initdb.d/init.sql

  bot_valins_ta-sdi_devel:
    build: ./
    container_name: telebot
    depends_on:
      - mysql_server
    links:
      - mysql_server
    networks:
      - bot_telegram_devel
    volumes:
      - ./files:/files

networks:
  bot_telegram_devel:

volumes:
  mysql_data:
    external: true

